apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
namespace: default
images:
  - name: ghcr.io/Kittinutz/jenosize-backend
    newTag: v0.0.4
