apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenosize-frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenosize-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenosize-frontend
    spec:
      containers:
        - name: jenosize-frontend
          image: ghcr.io/kittinutz/jenosize-frontend:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 4096Mi
          envFrom:
            - secretRef:
                name: frontend-secret
          readinessProbe:
            httpGet:
              path: '/'
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: github
