apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: default
images:
- name: ghcr.io/Kittinutz/jenosize-fe
  newTag: v0.0.11
- name: ghcr.io/Kittinutz/jenosize-frontend
  newTag: v0.0.17
