apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt'
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  name: jenosize-backend-ingress
  namespace: default
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api-jenosize.kittinut.com
      secretName: argocd-dashboard-tms-tls
  rules:
    - host: api-jenosize.kittinut.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenosize-backend
                port:
                  number: 3000
