apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt'
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-protocols: 'TLSv1.2 TLSv1.3'
    nginx.ingress.kubernetes.io/ssl-ciphers: 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'
    nginx.ingress.kubernetes.io/hsts: 'true'
    nginx.ingress.kubernetes.io/hsts-max-age: '31536000'
    nginx.ingress.kubernetes.io/hsts-include-subdomains: 'true'
    nginx.ingress.kubernetes.io/hsts-preload: 'true'
  name: jenosize-frontend-ingress
  namespace: default
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jenosize.kittinut.com
      secretName: jenosize-frontend-tls
  rules:
    - host: jenosize.kittinut.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenosize-frontend
                port:
                  number: 3000
